name: Dispatch Event

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: muram-105/B  # Replace with the username and repository name of Repository B

      - name: Dispatch Event to Repository B
        uses: peter-evans/repository-dispatch@v2
        with:
#           token: ${{ secrets.PAT_REPO_B }}  # Use the secret you created for Repository B
          token: ${{secrets.Token}}
          event-type: custom-event-type    # Replace with your custom event type
